### ISSUE TITLE
crash: Invalid Layer Save Flag

### ISSUE THREAD

**Issue by swat69** [vergecurrency/tordroid#4]
Device: LG G7, Android 10

2020-09-06 22:45:20.972 13872-13872/com.vergepay.wallet D/AndroidRuntime: Shutting down VM
2020-09-06 22:45:20.976 13872-13872/com.vergepay.wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vergepay.wallet, PID: 13872
    java.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
        at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:453)
        at android.graphics.Canvas.saveLayerAlpha(Canvas.java:640)
        at com.vergepay.wallet.ui.widget.SwipeProgressBar.draw(SwipeProgressBar.java:171)
        at com.vergepay.wallet.ui.widget.SwipeRefreshLayout.draw(SwipeRefreshLayout.java:328)
        at android.view.View.updateDisplayListIfDirty(View.java:20395)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.draw(View.java:21521)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:20395)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.updateDisplayListIfDirty(View.java:20386)
        at android.view.View.draw(View.java:21250)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4467)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4228)
        at android.view.View.draw(View.java:21521)
        at com.android.internal.policy.DecorView.draw(DecorView.java:863)
        at android.view.View.updateDisplayListIfDirty(View.java:20395)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:576)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:582)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:655)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3744)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3551)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2867)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1775)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7918)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1042)
        at android.view.Choreographer.doCallbacks(Choreographer.java:865)
        at android.view.Choreographer.doFrame(Choreographer.java:800)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1027)
        at android.os.Handler.handleCallback(Handler.java:883)
2020-09-06 22:45:20.976 13872-13872/com.vergepay.wallet E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-09-06 22:45:21.015 13872-13872/com.vergepay.wallet I/Process: Sending signal. PID: 13872 SIG: 9

**Comment by justinvforvendetta** [comment]
thanks for the report! did you do any particular action that this happened, or was it on startup/random/etc?

**Comment by swat69** [comment]
initial 'restore wallet' ok.
after that, crash on every startup immediately

[logcat.txt](https://github.com/vergecurrency/tordroid/files/5181774/logcat.txt)
[logcat2.txt](https://github.com/vergecurrency/tordroid/files/5181775/logcat2.txt)

**Comment by justinvforvendetta** [comment]
ok so crash happens from 28+ with swipeprogressbar. can u try the new upload in releases?

**Comment by justinvforvendetta** [comment]
i think this was fixed in https://github.com/vergecurrency/tordroid/commit/59afbef3b3e7f9f19ff9fb0a8942a61adaf48575

if not, please let me know and i will re open it.
